# Generated by Django 4.1.7 on 2023-06-26 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vacataire', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacataire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('dept', models.CharField(max_length=30, null=True)),
                ('fonction', models.CharField(choices=[('ingenieur', 'INGENIEUR'), ('Ing en chef ', 'INGENIEUR EN CHEF '), ('prof assistant ', 'PROF ASSISTANT'), ('PROF_ABILITE', 'PROF_ABILITE'), ('DOCTORANT', 'DOCTORANT'), ('PES', 'PES'), ('PROF AGREGE', 'PROF AGREGE')], max_length=50, null=True)),
                ('banque', models.CharField(max_length=50, null=True)),
                ('rib', models.CharField(max_length=50, null=True)),
                ('remuniration', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nbre_heure', models.IntegerField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='seance',
            name='Assignement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacataire.assignement'),
        ),
        migrations.AddField(
            model_name='presence',
            name='seance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vacataire.seance'),
        ),
        migrations.AddField(
            model_name='presence',
            name='vacataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activite', to='Vacataire.vacataire'),
        ),
        migrations.AddField(
            model_name='assignement',
            name='Vacataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignements', to='Vacataire.vacataire'),
        ),
        migrations.AddField(
            model_name='absence',
            name='seance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vacataire.seance'),
        ),
        migrations.AddField(
            model_name='absence',
            name='vacataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacataire.vacataire'),
        ),
    ]
