# Generated by Django 4.1.7 on 2023-06-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacataire', '0003_alter_assignement_fichier_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignement',
            old_name='Vacataire',
            new_name='vacataire',
        ),
    ]
